baseurl      = "https://michalbiesek.github.io"
title        = "Michal`s Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 5

[params]
  homeSubtitle = "OS, software and other stuff"
  keywords = "riscv, ebpf, system library"
  images = [""]

  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    ]

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [[params.social]]
    name = "github"
    url = "https://github.com/michalbiesek/"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/michal-b-17955686/"

[author]
  name = "Michal Biesek"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Michal`s Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.en.params.logo]
      logoText = "This mission is too important for me to allow you to jeopardize it.."
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
